### ISSUE TITLE
The sdk for v2 factory not working.

### ISSUE THREAD

**Issue by aak-dev** [pancakeswap/pancake-swap-interface-v1#399]
The app I am building uses pancakswap's sdk to get swap pricing and after the v2 migration the sdk pointing to v1 factory is using old prices and if I change the address to v2 the sdk is not working.

**Comment by aak-dev** [comment]
we made an sdk to work with pcs v2. 
Checkout https://www.npmjs.com/package/@overage69/pancake-sdk-v2

**Comment by WalkerWang731** [comment]
awasome!

**Comment by ChefKai** [comment]
Repository: https://github.com/pancakeswap/pancake-swap-sdk
NPM: https://www.npmjs.com/package/@pancakeswap/sdk
