### ISSUE TITLE
Problems with Contract and Pancakeswap V2 Router

### ISSUE THREAD

**Issue by sunalo** [pancakeswap/pancake-swap-interface-v1#421]
Hello, i have a BEP20 Token, with 3% burn and 3% tax every buy/sell.

sine yesterday its every time 0%. 
Here you see befor and after. But in Contract (Source Code) is the tax and burn rate still 3%.

![Bildschirmfoto 2021-05-13 um 20 12 11](https://user-images.githubusercontent.com/13155606/118167940-92875900-b427-11eb-93ac-dc56c20675ff.png)
![Bildschirmfoto 2021-05-13 um 20 11 50](https://user-images.githubusercontent.com/13155606/118167944-931fef80-b427-11eb-97fe-9c2bb1d34830.png)

**Comment by sunalo** [comment]
The first picture is befor, the second (after)

**Comment by Chef-Chungus** [comment]
This is an issue with your token, not the router

**Comment by sunalo** [comment]
> This is an issue with your token, not the router

Can you maybe check for me, because we search now the hole day and didn't find any support or solution.
https://bscscan.com/token/0xced0b3b9f30f12332c77ad937d6137ce94162d9d

**Comment by sunalo** [comment]
I checked. we try to send from wallet to wallet. here is burn and fee working.
i open a small pool in BakerySwap. Here is working as well with tax and fee, burn rate.

So its only with all  buy and sells over Pancakeswap Contract. 
Can i refresh this contract manuell? or something

**Comment by Chef-Chungus** [comment]
I assume you have whitelisted the router to not be charged fees.

**Comment by Chef-Chungus** [comment]
Either way, this is not a problem with the router, it is a problem with your token. 

I'll be closing this issue as its something we can't help with
