### ISSUE TITLE
Missing funds

### ISSUE THREAD

**Issue by vkamov** [pancakeswap/pancake-swap-interface-v1#440]
Hi,

All my funds are missing from Pancakeswap. How to recover?

**Comment by Chef-Chungus** [comment]
We don't hold any of users funds.

Please check your wallet, and check if it was compromised

**Comment by vkamov** [comment]
Nothing in the wallet. Apart from BNB. Not comprimised.

**Comment by vkamov** [comment]
Cakes are not shown in the pools. Also missing funds from farms
