### ISSUE TITLE
/api/tokens 500 (Internal Server Error)

### ISSUE THREAD

**Issue by ubuntutest** [pancakeswap/pancake-swap-interface-v1#445]
since this morning I'm experiencing error 500, what does it depend on?

GET https://api.pancakeswap.info/api/tokens 500 (Internal Server Error)

![a2a2cd820d3e6282eb752cf3a32de4b9](https://user-images.githubusercontent.com/13025037/123086700-0a33a500-d424-11eb-881e-1dccb8223c8c.png)

**Comment by ChefKai** [comment]
This has been fixed, thank you for your report.
